### ISSUE TITLE
Chat-Fenster nicht responsiv bei aufgeklappter Tastatur

### ISSUE THREAD

**Issue by lwiedema** [FelipGC/MSP_ProjectKickOff_SS188#4]
Beim Aufklappen der Soft-Tastatur wird das Layout nach oben verschoben, sodass die ersten Nachrichten einer Unterhaltung nach dem Abschicken für den Sender nicht sichtbar sind.

Erwartbar wäre, dass die Actionbar sichtbar bleibt und die gesendete Nachricht auch bei geöffneter Tastatur für den Nutzer sichtbar ist. 

| ![screenshot_1528203233](https://user-images.githubusercontent.com/19931832/40977132-676b40ce-68d0-11e8-9448-bfcb4c077a1d.png) | ![screenshot_1528203242](https://user-images.githubusercontent.com/19931832/40977133-678895f2-68d0-11e8-8014-6b8c7f924f2a.png) | ![screenshot_1528203245](https://user-images.githubusercontent.com/19931832/40977134-67a99c0c-68d0-11e8-9f34-67e0b4204f75.png) | ![screenshot_1528203248](https://user-images.githubusercontent.com/19931832/40977136-67c6b396-68d0-11e8-8531-5e592ef84811.png) | 
|---|---|---|---|

**Comment by FelipGC** [comment]
Die Tastatur sollte sich auch automatisch schließen nachdem man eine Nachricht eingetippt und versendet hat

**Comment by lwiedema** [comment]
Das ist Ansichts- und Geschmacksache 🤔

**Comment by EliT1995** [comment]
Ich würde es offen lassen

**Comment by lwiedema** [comment]
Durch Umbau von ActionBar zu Toolbar mit Pullrequest #8 behoben.

**Comment by lwiedema** [comment]
Erste Nachrichten noch immer nicht im sichtbaren Bereich
